name: Create github release

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:

  build-and-unit-test:
    uses: ./.github/workflows/reusable-build-and-unit-test.yml

  publish:
    runs-on: ${{ matrix.operating-system }}
    needs: build-and-unit-test

    strategy:
      matrix:
        operating-system: [windows-latest]   

    steps:
    - uses: actions/checkout@v4
    - name: List Directory
      run: ls -R
    - name: Publish
      run: dotnet publish --configuration Release --no-build --verbosity normal --output /dist ../../../src/FileSorter.Console/FileSorter.Console.csproj


