name: Create github release

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:

  build-and-unit-test:
    uses: ./.github/workflows/reusable-build-and-unit-test.yml

  publish:
    runs-on: ${{ matrix.operating-system }}
    needs: build-and-unit-test

    strategy:
      matrix:
        operating-system: [windows-latest]   

    steps:
    - name: Download solution artifact
      uses: actions/download-artifact@main
      with:
        name: Solution artifact
    - name: Test solution artifact download
      run: ls -R
    - uses: actions/checkout@v4
    - name: List Directory
      run: ls -R
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --verbosity normal --output /dist D:\a\file-sorter\file-sorter\src\FileSorter.Console\FileSorter.Console.csproj


