name: Build and test

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: List Directory
      run: ls -R
    - name: Upload build artifact
      uses: actions/upload-artifact@main
      with:
        name: Build artifact
        path: ./test/FileSorter.UnitTest/bin/Release/
        if-no-files-found: error
 
  test:
    runs-on: ${{ matrix.operating-system }}
    needs: build
    
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]    

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@main
        with:
          name: Build artifact
      - name: Test build artifact download
        run: ls -R
      - name: Test
        run: dotnet test */FileSorter.UnitTest.dll --no-build --verbosity normal
